### ISSUE TITLE
Graphic cards hanging down due missing holder

### ISSUE THREAD

**Issue by magdesign** [system76/thelio#4]
On my Thelio the graphics card is kind of hanging down.

To fix this, I made the first modification on the case:
Cutting 2x M3 threads and fit in a screw to hold the weight of the cards. See attached pictures.
![m3_slot_stabilizer2](https://user-images.githubusercontent.com/5273166/54078572-898c2180-42ca-11e9-9a30-68836f8ce5a8.JPG)

![m3_slot_stabilizer](https://user-images.githubusercontent.com/5273166/54078556-4df15780-42ca-11e9-8152-683dc100f3fa.JPG)

**Comment by brs17** [comment]
Thank you for the feedback @magdesign ! We really appreciate it.

Since you received your Thelio, we have since made some changes to the pcie bracket with a similar solution in mind (notice the ridges holding the graphics card up):

![pcieimprovements](https://user-images.githubusercontent.com/7460774/54313924-ed02a180-459f-11e9-9225-cd5ab3520322.JPG)

I expect the team to be in touch with you regarding these changes.

**Comment by eric-s-raymond** [comment]
I've seen a similar issue with my Thelio.  Graphics card fell partway out of its slot when I had the machine case off and resting on its front so I could have easy access to the rear-side ports.  Clearly it wan't secured enough.
