### ISSUE TITLE
Thermal Testing on Major V3 Chassis

### ISSUE THREAD

**Issue by jgrano** [system76/thelio#40]
Verify Thermal performance with V3 chassis vs V2.

**Comment by leviport** [comment]
I'm still waiting on the thick spinner drives, but here's my evaluation so far. 

With two non-blower cards installed (2080 and 2080Ti), I was able to make the CPU throttle some while stressing the CPU, RAM, and both GPUs at the same time. If I only stressed the CPU and RAM, the CPU would hover around 93°C and run at full speed. The GPU in the top slot (the 2080 in this case) throttled quite a bit after about 10 minutes of stressing, but that's not a surprise since it's a non-blower with another non-blower directly below it.

When I switched the GPUs out for two blower cards (both were 2080Ti's), things got much better. The CPU and both GPUs would get close to their max temps, but throttling was extremely minimal.

**Comment by leviport** [comment]
We received the drives and began testing. We loaded all 4 into the top bay first. The drives jumped up to 55°C very quickly. In prior testing, they started keeling over if they got much above that, so I halted the test.

The fan does not fit over the top of this bay with the top case on, so I haven't been able to test that yet. I might drill new holes to move this drive bay down a bit so I can get it in there.

I will test the lower bay next. Since it's right next to the bottom intake fan, I want to see how it does with out the 90mm cover fan first.

**Comment by leviport** [comment]
The drives seem to be staying plenty cool in the lower bay without the 90mm fan lid. Current max temp is 43°C after about 5 hours of stressing. So if we end up needing the fan lid, it'll only be needed on the top bay.

**Comment by jgrano** [comment]
So to accommodate the 1% of users that will utilize all 8 bays I will move the upper cage down to be able to handle a 90mm fan.

**Comment by jgrano** [comment]
@brs17 @leviport This would need to get integrated into the catalog as well as associated with only adding for the fully loaded spinning disk systems - 

https://noctua.at/en/nf-a9x14-pwm-chromax-black-swap

**Comment by brs17** [comment]
> @brs17 @leviport This would need to get integrated into the catalog as well as associated with only adding for the fully loaded spinning disk systems -
> 
> https://noctua.at/en/nf-a9x14-pwm-chromax-black-swap

For sure. V3 update will require at least one other catalog update as well. As we get closer to being ready with V3, all of that will need to be figured out, those fans sourced/priced, V2s phased out, and production brought up to speed in regards to transitioning to V3.

**Comment by leviport** [comment]
I'd like to test the drive cover with the fan when it's ready, but I believe that's the last remaining thermal question remaining with this prototype.

**Comment by jgrano** [comment]
@leviport I can't seem to make a 90mm fan work right for mounting with the cage as it is now. I'm going to try building around a NF-A6x25 pwm Noctua fan. I think it will push enough air and actually have the right pattern for me to mount.

**Comment by jgrano** [comment]
Scrapping lower cage location and pushing parts backup. Per recheck of old thermals
