### ISSUE TITLE
Thelio case needs better noise suppression

### ISSUE THREAD

**Issue by eric-s-raymond** [system76/thelio#5]
I recently moved to a Thelio (generously donated by System76!) from a custom-built system with a high-end sort-of-gamer case called an NZXT (Model 700, I think).  I say "sort-of-gamer" because it used design ideas from gamer hotrod systems while obviously being intended for a broader market - lots of focus on maintainability and upgrade-friendliness in the design.

One axis along which that case was well ahead of the Thelio's is sound suppression.  Besides the now-usual 200mm slow-rotation fans. It did two things future revs of the case could usefully copy:

(1) A thin layer of acoustic foam on the inner walls of the case to absorb sound and dampen case vibrations.  

(2) Contract points between assemblies are often (not always, but often) but often acoustically damped by rubber grommets or feet.

If you do these things, it is possible for a Thelio-class system to be whisper-quiet. I miss that about my old system.

**Comment by magdesign** [comment]
The noise is really an annoying issue which needs to be resolved.
I will try the rubber idea...

**Comment by WatchMkr** [comment]
Thank you for the suggestions. We're working on acoustic improvements in Thelio Io firmware (where we've found lots of potential for optimization) and Thelio mechanical design.

**Comment by eric-s-raymond** [comment]
Yeah, that relatively thin case top with no damping on the joints to the base could have been designed as a noise ampilifier.  Grommeting at the joints would address this.

**Comment by magdesign** [comment]
I removed this:
![Removed_This](https://user-images.githubusercontent.com/5273166/57971199-2f26d580-798b-11e9-84fc-d49c5ab38607.jpg)

and added some rubber tape on top:
![added_rubbertape](https://user-images.githubusercontent.com/5273166/57971210-3e0d8800-798b-11e9-8eaf-fa6e2a6c38f1.jpg)

Now to noise is a bit less high....

**Comment by avollmerhaus** [comment]
How loud does it usually get? I considered buying a Thelio (the little one), but I can't stand fan noise.
I will be doing some compiling on the system (gentoo user), so it would be a real show stopper if the system is noisy all the time.

**Comment by magdesign** [comment]
To be honest, its quite noisy!
I added several rubber tape pieces everywhere to make it more silent, but with heavy rendering I  hear the fans and they speed up and down all the time which makes it really annoying. A constant sound would be a bit less nerve killing....
However, I guess its still one of the best opensource system available.

**Comment by labeledmk** [comment]
Some flaws in the design acoustically speaking would be no soft gaskets used, the gap between the chassis and the top shell, the fans. Soft gaskets between vibration points such as fans or the cpu shrouds would help some. The design used on the exhaust and bottom intake are cool but they're thin so you need to isolate them from vibrating as much as possible. The gap on the bottom would be helped with some sort of air filter or being closed altogether. Any open point in the system will leak sound and keeping as much sound coming out of the exhaust as possible will help overall perception of audible sound escaping. The fans are trickier it's a combination of blades, bearing, and fan profiles. Better cooler pulling the heat away from the cpu will mean you can get away with lower RPMs. So thermal paste to something higher their could help though I'm not sure what you do use and how it compares.

**Comment by WatchMkr** [comment]
Over the past year and a half, we've worked to dramatically improve the acoustic characteristics of Thelio. We can now confidently close this issue. Most of these changes have been in since late last year. We had a couple more fan curves to optimize when COVID hit which delayed our closing of this issue.

Improving Thelio acoustic quality included component, mechanical, and software changes. To begin the process we built a sound proof room in our factory and acquired testing equipment to measure decibels in a controlled environment. This provided the data necessary to establish a baseline and measure the affect of our changes.

![IMG_4218](https://user-images.githubusercontent.com/3430283/91600611-7ab58680-e925-11ea-9ac5-4d24fce1e493.jpg)

**Components**

We have moved to entirely Noctua or Be Quiet fans and coolers. They provide rubber dampening and quieter motors. We use both because supply from only one is not consistent enough. However, we have found that their products perform equally well with regard to cooling and acoustics.

A considerable amount of noise for early shipments of Thelio Major and Massive came from the power supply. EVGA power supplies have a "Eco Mode" that must be turned on to enable a fan curve for the power supply. For Major and Massive customers, please check that Eco Mode is turned on if the power supply seems loud. The switch is either on the back or inside on the power supply. Fan curves on power supplies are now required or enabled on all shipments. Enabling Eco Mode has no affect on performance. It's a silly switch that shouldn't exist. 

![IMG_4220](https://user-images.githubusercontent.com/3430283/91601034-34145c00-e926-11ea-824d-f4daa81b1761.jpg)

**Mechanical**

Fans are now attached to ducts in the system rather than to the coolers. This reduces transit damage and vibrations when paired with rubber dampeners.

Before
![IMG_4223](https://user-images.githubusercontent.com/3430283/91601257-8c4b5e00-e926-11ea-81ba-e6563d9e2ab8.jpg)

After (Also notice the chamber now pulls cool air for Major HEDT CPUs directly from the outside of the chassis. This resulted in better performance and quieter operation.)
![IMG_4224](https://user-images.githubusercontent.com/3430283/91601308-a84eff80-e926-11ea-997c-be9c92dbe183.jpg)

In early Thelio models, there was a gap between the exterior and interior at the bottom of the machine. We extended the sides of the bottom out to seal the top and bottom of the chassis. 

Before
![IMG_4219](https://user-images.githubusercontent.com/3430283/91601586-23181a80-e927-11ea-9a05-dc9e44baed09.jpg)

After 
![IMG_4221](https://user-images.githubusercontent.com/3430283/91601541-1398d180-e927-11ea-85b1-dc78e89034ef.jpg)

**Software**

While components and mechanical changes contributed to improvements, the biggest improvement came from carefully designed fan curves for each class of product. Fan curve optimizations improved system performance and acoustics. This blog post goes into more detail: https://blog.system76.com/post/618130916327456768/keeping-cool-with-thelio-the-secrets-of-thelios

Being that the biggest contributor to improving Thelio acoustic qualities was software, the improvements have shipped to all Thelio customers through software updates to the system76-power package. All curves for all products have now been optimized and the updates shipped.
